# Generated by Django 6.0.2 on 2026-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_comments', '0002_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
