# Generated by Django 6.0.2 on 2026-03-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0002_board_members_alter_board_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
    ]
