# Generated by Django 6.0.2 on 2026-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0003_remove_board_member_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleBoard',
        ),
    ]
