# Generated by Django 6.0.2 on 2026-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0004_delete_singleboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
    ]
