# Generated by Django 6.0.2 on 2026-03-11 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0005_alter_board_options_and_more'),
        ('kanban_tasks', '0002_task_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board'], name='kanban_task_board_i_3424b8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='kanban_task_assigne_aa8842_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reviewer'], name='kanban_task_reviewe_f703a7_idx'),
        ),
    ]
