# Generated by Django 6.0.2 on 2026-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_tasks', '0003_task_kanban_task_board_i_3424b8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'Todo'), ('in-progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], max_length=100),
        ),
    ]
